/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Helmet: typeof import('react-helmet-async')['Helmet']
  const Link: typeof import('@tanstack/react-router')['Link']
  const Outlet: typeof import('@tanstack/react-router')['Outlet']
  const QueryClient: typeof import('@tanstack/react-query')['QueryClient']
  const QueryClientProvider: typeof import('@tanstack/react-query')['QueryClientProvider']
  const createFileRoute: typeof import('@tanstack/react-router')['createFileRoute']
  const createLazyFileRoute: typeof import('@tanstack/react-router')['createLazyFileRoute']
  const createRef: typeof import('react')['createRef']
  const createRootRouteWithContext: typeof import('@tanstack/react-router')['createRootRouteWithContext']
  const forwardRef: typeof import('react')['forwardRef']
  const getApi: typeof import('@tanstack/react-router')['getApi']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMutation: typeof import('@tanstack/react-query')['useMutation']
  const useQuery: typeof import('@tanstack/react-query')['useQuery']
  const useQueryClient: typeof import('@tanstack/react-query')['useQueryClient']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSuspenseQuery: typeof import('@tanstack/react-query')['useSuspenseQuery']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
