/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as DashboardBoardsRouteImport } from './routes/dashboard.boards/route'
import { Route as DashboardBoardsSlugRouteImport } from './routes/dashboard.boards.$slug/route'
import { Route as DashboardBoardsSlugTaskTaskIdRouteImport } from './routes/dashboard.boards.$slug.task.$taskId/route'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthLoginLazyImport = createFileRoute('/_auth/login')()
const AuthJoinLazyImport = createFileRoute('/_auth/join')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRouteRoute = DashboardRouteImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/route.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.login.lazy').then((d) => d.Route))

const AuthJoinLazyRoute = AuthJoinLazyImport.update({
  path: '/join',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth.join.lazy').then((d) => d.Route))

const DashboardBoardsRouteRoute = DashboardBoardsRouteImport.update({
  path: '/boards',
  getParentRoute: () => DashboardRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard.boards/route.lazy').then((d) => d.Route),
)

const DashboardBoardsSlugRouteRoute = DashboardBoardsSlugRouteImport.update({
  path: '/$slug',
  getParentRoute: () => DashboardBoardsRouteRoute,
} as any).lazy(() =>
  import('./routes/dashboard.boards.$slug/route.lazy').then((d) => d.Route),
)

const DashboardBoardsSlugTaskTaskIdRouteRoute =
  DashboardBoardsSlugTaskTaskIdRouteImport.update({
    path: '/task/$taskId',
    getParentRoute: () => DashboardBoardsSlugRouteRoute,
  } as any).lazy(() =>
    import('./routes/dashboard.boards.$slug.task.$taskId/route.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/boards': {
      preLoaderRoute: typeof DashboardBoardsRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/_auth/join': {
      preLoaderRoute: typeof AuthJoinLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthImport
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/boards/$slug': {
      preLoaderRoute: typeof DashboardBoardsSlugRouteImport
      parentRoute: typeof DashboardBoardsRouteImport
    }
    '/dashboard/boards/$slug/task/$taskId': {
      preLoaderRoute: typeof DashboardBoardsSlugTaskTaskIdRouteImport
      parentRoute: typeof DashboardBoardsSlugRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DashboardRouteRoute.addChildren([
    DashboardBoardsRouteRoute.addChildren([
      DashboardBoardsSlugRouteRoute.addChildren([
        DashboardBoardsSlugTaskTaskIdRouteRoute,
      ]),
    ]),
    DashboardIndexRoute,
  ]),
  AuthRoute.addChildren([AuthJoinLazyRoute, AuthLoginLazyRoute]),
])

/* prettier-ignore-end */
